[package]
name = "buzzdebug"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = { workspace = true }
bevy-inspector-egui = "0.25.2"
lightyear = { workspace = true }
serde = { version = "1.0.209", features = ["derive"] }
zusammen_plugin = { path = "../zusammen_plugin" }
