[package]
name = "zusammen_app"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = { workspace = true }
clap = "4.5.16"
crossbeam-channel = "0.5.13"
lightyear = { workspace = true }
rand = "0.8.5"
zusammen_plugin = { path = "../zusammen_plugin" }
